apiVersion: v1
kind: Namespace
metadata:
  name: homebox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox-deployment
  namespace: homebox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebox
  template:
    metadata:
      labels:
        app: homebox
    spec:
      containers:
        - name: homebox
          image: ghcr.io/sysadminsmedia/homebox:main-rootless
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "120Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: homebox-service
  namespace: homebox
spec:
  selector:
    app: homebox
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homebox-ingress
  namespace: homebox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  rules:
    - host: inv.jank.engineer
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homebox-service
                port:
                  number: 8080
  tls:
    - hosts:
        - inv.jank.engineer
      secretName: homebox-tls

