---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /opt/forgejo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node/gizmo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pvc
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: forgejo-helm
  namespace: forgejo
spec:
    interval: 5m0s
    url: oci://code.forgejo.org/forgejo-helm/forgejo
    ref:
      tag: 11.0.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app
  namespace: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-helm
  interval: 5m0s
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      tls:
        - hosts:
            - git.critter.codes
          secretName: ingress-tls
    postgresql:
      enabled: true
      existingClaim: forgejo-pvc
    persistence:
      enabled: true
      existingClaim: forgejo-pvc
    gitea:
      config:
        APP_NAME: "critters' forge"
