---
apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo-helm
  namespace: forgejo
spec:
  interval: 5m0s
  url: oci://code.forgejo.org/forgejo-helm/forgejo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  chart:
    spec:
      chart: forgejo
      sourceRef:
        kind: HelmRepository
        name: forgejo-helm
      version: 11.0.1
  interval: 10m
  values:
    service:
      type: ClusterIP
      port: 5012
      name: http
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts:
        - host: git.critter.codes
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - git.critter.codes
          secretName: forgejo-tls
    persistence:
      enabled: true
      existingClaim: forgejo-pvc
    postgresql:
      enabled: true
      existingClaim: forgejo-pvc
    gitea:
      config:
        APP_NAME: "critters' forge"
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
