---
apiVersion: v1
kind: Namespace
metadata:
  name: penpot
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: penpot
  namespace: penpot
spec:
  interval: 5m0s
  url: https://helm.penpot.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
  namespace: penpot
spec:
  chart:
    spec:
      chart: penpot
      sourceRef:
        kind: HelmRepository
        name: penpot
      version: 0.10.0
  interval: 10m
  values:
    ingress:
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts: ["penpot.jank.engineer"]
      tls:
        - hosts:
            - penpot.jank.engineer
          secretName: penpot-tls
    config:
      publicUri: "https://penpot.jank.engineer"
      registrationDomainWhitelist: "critter.codes"

