---
apiVersion: v1
kind: Namespace
metadata:
  name: webbedsite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webbedsite
  namespace: webbedsite
spec:
  selector:
    matchLabels:
      app: webbedsite
  template:
    metadata:
      labels:
        app: webbedsite
    spec:
      containers:
      - name: webbedsite
        image: ghcr.io/isjustcat/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1312
---
apiVersion: v1
kind: Service
metadata:
  name: webbedsite
  namespace: webbedsite
spec:
  selector:
    app: webbedsite
  ports:
  - name: http
    port: 1312
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webbedsite
  namespace: webbedsite
annotations:
  cert-manager.io/cluster-issuer: letsencrypt-http
labels:
  name: webbedsite
spec:
  tls:
    - secretName: webbedsite-tls
      hosts:
        - critter.codes
  rules:
    - host: critter.codes
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webbedsite
                port:
                  name: http
  