apiVersion: v1
kind: Namespace
metadata:
  name: actualbudget
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: actualbudget-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: "/mnt/data/actualbudget"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-pvc
  namespace: actualbudget
spec:
  storageClassName: local-path
  volumeName: actualbudget-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
  namespace: actualbudget
spec:
  interval: 5m0s
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  chart:
    spec:
      chart: actualbudget
      sourceRef:
        kind: HelmRepository
        name: community-charts
  interval: 10m
  values:
    service:
      type: ClusterIP
      # port: 5013
      name: http
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts:
        - host: budget.jank.engineer
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - budget.jank.engineer
          secretName: actualbudget-tls
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"
    persistence:
      enabled: true
      existingClaim: actualbudget-pvc
    files:
      server: /mnt/data/server-files
      user: /mnt/data/user-files
    strategy: recreate
