apiVersion: v1
kind: Namespace
metadata:
  name: actualbudget
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
  namespace: actualbudget
spec:
  interval: 5m0s
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  chart:
    spec:
      chart: actualbudget
      sourceRef:
        kind: HelmRepository
        name: community-charts
  interval: 10m
  values:
    service:
      type: ClusterIP
      port: 5013
      name: http
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts:
        - host: budget.jank.engineer
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - budget.jank.engineer
          secretName: actualbudget-tls
    resources:
      requests:
        cpu: "50m"
        memory: "120Mi"

