apiVersion: v1
kind: Namespace
metadata:
  name: borgserver
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: borgserver-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/borgserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borgserver-pvc
  namespace: borgserver
spec:
  resources:
    requests:
      storage: 15Gi
  volumeName: borgserver-pv
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borgserver-deployment
  namespace: borgserver
  labels:
    app: borgserver
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: borgserver-pvc
  replicas: 1
  selector:
    matchLabels:
      app: borgserver
  template:
    metadata:
      labels:
        app: borgserver
    spec:
      containers:
        - name: borgserver
          image: borgserver
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          volumeMounts:
            - name: data
              mountPath: /
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: borgserver-service
  namespace: borgserver
spec:
  selector:
    app: borgserver
  ports:
  - protocol: TCP
    port: 22
    nodePort: 2222
  type: NodePort