---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m0s
  url: https://charts.goauthentik.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
      version: 2025.2.2
  interval: 10m
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secret
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-postgresql
      valuesKey:  password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-postgresql
      valuesKey:  password
      targetPath: authentik.postgresql.password
  values:
    server:
      env:
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-password
              key: password
      name: "meow"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-dns
        tls:
          - secretName: authentik-tls
            hosts: 
              - a.jank.engineer
        hosts:
          - a.jank.engineer
    postgresql:
      enabled: true
    redis:
      enabled: true
