---
apiVersion: v1
kind: Namespace
metadata:
  name: c3gock
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mastodon/chart
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mastodon
  namespace: c3gock
spec:
  interval: 10m
  chart:
    spec:
      chart: mastodon
      sourceRef:
        kind: GitRepository
        name: mastodon
  values:
    smtp:
      auth_method: plain
      delivery_method: smtp
      enable_staarttls: "auto"
      from_address: "mastodoof@jank.engineer"
      port: 465
      server: "mail.e926.de"
      existingSecret: "smtp-secrets"
      
    mastodon:
      local_domain: "c3gock.de"
      authorizedFetch: true
      createAdmin:
        enabled: true
        username: admin
        email: c3gock@critter.codes
      secrets:
        existingSecret: "masto-secrets"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
      hosts:
        - host: c3gock.de
          paths:
            - path: "/"
      tls:
        - secretName: c3gock-tls
          hosts:
            - c3gock.de 
