---
apiVersion: v1
kind: Namespace
metadata:
  name: c3gock
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: c3gock
  namespace: c3gock
spec:
  chart:
    spec:
      chart: mastodon
      sourceRef:
        kind: HelmRepository
        name: mastodon
      version: 9.2.7
  interval: 10m
