apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: photoprism
  namespace: photoprism
spec: 
  interval: 1h
  url: https://p80n.github.io/photoprism-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: photoprism
spec:
  chart:
    spec:
      chart: photoprism
      sourceRef:
        kind: HelmRepository
        name: photoprism
        namespace: photoprism
      version: 1.4.0
  interval: 1h
  values:
    ingress:
      enabled: true
      className: nginx
      tls:
        - hosts:
            - pics.jank.engineer
          secretName: photoprism-tls
