apiVersion: v1
kind: Namespace
metadata:
  name: photoprism
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism
  namespace: photoprism
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/photoprism
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        ports:
          - containerPort: 2342
        env:
          - name: PHOTOPRISM_ADMIN_USER
            value: "admin"
          - name: PHOTOPRISM_ADMIN_PASSWORD
            value: "insecure"
          - name: PHOTOPRISM_DATABASE_DRIVER
            value: "sqlite"
          - name: PHOTOPRISM_DATABASE_NAME
            value: "photoprism.db"
          - name: PHOTOPRISM_STORAGE_PATH
            value: "/photoprism"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
          - name: photoprism
            mountPath: /photoprism
      volumes:
        - name: photoprism
          persistentVolumeClaim:
            claimName: photoprism
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: photoprism
spec:
  type: ClusterIP
  ports:
    - port: 2342
      targetPort: 2342
  selector:
    app: photoprism
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  labels:
    name: photoprism
  namespace: photoprism
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pics.jank.engineer
      secretName: photoprism-tls
  rules:
  - host: pics.jank.engineer
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: photoprism
            port: 
              number: 2342