---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 10m
  url: https://guerzon.github.io/vaultwarden
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: vaultwarden
  name: vaultwarden-db
spec:
  instances: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1
      memory: 128Mi
  storage:
    size: 1Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 10m
  chart:
    spec:
      chart: vaultwarden
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 10m
  values:
    domain: "https://pwn.jank.engineer"
    signupsAllowed: false
    adminToken:
      existingSecret: vaultwarden-admin-token
      existingSecretKey: masterkey
    database:
      type: postgresql
    admin:
      enabled: true
      existingSecret: vaultwarden-admin-token
    ingress:
      enabled: true
      hostname: "https://pwn.jank.engineer"
      tls: true
      tlsSecret: vaultwarden-tls
      class: traefik
      additionalAnnotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
        limits:
          memory: 1Gi
  valuesFrom:
    - kind: Secret
      name: vaultwarden-db-app
      valuesKey: uri
      targetPath: database.uriOverride