apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gissilabs
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://gissilabs.github.io/charts/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/vaultwarden/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  storageClassName: local-path
  volumeName: vaultwarden-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden-release
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: gissilabs
      version: 1.2.5
  interval: 10m
  values:
    service:
      type: ClusterIP
      httpPort: 8012
      externalTrafficPolicy: Cluster
    ingress:
      enabled: true
      host: pwn.jank.engineer
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      tls:
        - hosts:
            - pwn.jank.engineer
          secretName: vaultwarden-tls
      persistence:
        enabled: true
        size: 1Gi
        accessMode: ReadWriteOnce
        existingClaim: vaultwarden-pvc
      resources:
        requests:
          cpu: "50m"
          memory: "120Mi"