apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 5m0s
  url: https://guerzon.github.io/vaultwarden
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /mnt/data/vaultwarden/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  storageClassName: local-path
  volumeName: vaultwarden-pv
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden-release
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
      version: 0.31.6
  interval: 10m
  values:
    domain: "https://pwn.jank.engineer"
    ingress:
      enabled: true
      class: nginx
      hostnme: pwn.jank.engineer
      additionalAnnotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
      tls: true
      tlsSecret: vaultwarden-tls
    existingVolumeClaim:
      claimName: vaultwarden-pvc
      size: 5G
      class: local-path
      keepPvc: true
    resources:
      requests:
        cpu: 100m
        memory: 1G
    image:
      pullPolicy: always
    service:
      httpPort: 8080
